//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just_Search_UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Just_Search_UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;&lt;html dir=&quot;ltr&quot; lang=&quot;da&quot; class=&quot;html5 appsHeaderFooter da-dk rebranded&quot;&gt;
        ///&lt;head id=&quot;head&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;var jeTimerStart = (typeof Date.now === &quot;function&quot;) ? Date.now() :  +new Date();&lt;/script&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;
        ///    
        ///    &lt;title&gt;Deep Pan Pizza Express Take Away Menu i Viborg | Bestil Fra JUST EAT&lt;/title&gt;
        ///    
        ///&lt;meta name=&quot;keywords&quot; content=&quot; &quot; /&gt;
        ///
        ///    
        ///&lt;meta name=&quot;description&quot; content=&quot;Se det  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JustEatMenuUnitTest {
            get {
                return ResourceManager.GetString("JustEatMenuUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;&lt;html dir=&quot;ltr&quot; lang=&quot;da&quot; class=&quot;html5 appsHeaderFooter da-dk rebranded&quot;&gt;
        ///&lt;head id=&quot;head&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;var jeTimerStart = (typeof Date.now === &quot;function&quot;) ? Date.now() :  +new Date();&lt;/script&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;
        ///    
        ///    &lt;title&gt;Anmeldelser af Deep Pan Pizza Express i Viborg, 8800 | JUST EAT&lt;/title&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;Se information om Deep Pan Pizza Express i Viborg. Læs andr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JustEatUnitTest {
            get {
                return ResourceManager.GetString("JustEatUnitTest", resourceCulture);
            }
        }
    }
}
